variables:
  LC_ALL: C.UTF-8
  LANG: en_US.UTF-8
  LANGUAGE: en_US.UTF-8

stages:
  - build

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - |
      echo "-----BEGIN CERTIFICATE-----
MIIFBTCCAu2gAwIBAgIBADANBgkqhkiG9w0BAQsFADBGMQwwCgYDVQQGEwNVU0Ex
DzANBgNVBAoMBkdpdExhYjESMBAGA1UECwwJQ29udGFpbmVyMREwDwYDVQQDDAhS
ZWdpc3RyeTAeFw0xNzAxMjIyMzQ4MTRaFw0yNzAxMjAyMzQ4MTRaMEYxDDAKBgNV
BAYTA1VTQTEPMA0GA1UECgwGR2l0TGFiMRIwEAYDVQQLDAlDb250YWluZXIxETAP
BgNVBAMMCFJlZ2lzdHJ5MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA
t5nzNqlt6RC1GyUwcav1qFqMVKQbihgCEdRjFl6gebP7T+oLkWSD2I1SDr9KU9xs
zrfurN50pgkvzc5HQa+ZrS0nOAunEpA92Xp1HYR/TMaiR4eUo279/dnIBdpHsycA
GyYHcGFRRvy6pgglw9d3d40J7BjAOuGU7qhmRv+ALBF3tVG1+Gr+6p9Dk5YxJ+pV
KNQdqPJCmOgNTfXM3JMiWhBof72kBLl1KxRNxlaHmcah5S5W6r5HeXXJ1yjDaRuS
FMnjsfb0IoyfwGSJpuNRTw22j8zUDU7lMuFXC9pat8Q1UzTd3NZR+rjdtQXfALjJ
yRtGDguD8f9GvsTLi9kbanWzrXxedVQnG6mHNIRrXca2NnjMnD3bCjQuWMQuIea2
qo5YL4GH+0HYpg/+xyrP9FheeA3bVs6ANk5YxRXEAO4ym98ctkVSNuRkjxrWBw2x
l3RFAQWNIWifHVkXcB6+2NEDWwyn6JGbi/DqXX8QdPjqFXLlqNRuh6DBzez41Vnq
DL+9yzW/LJU1MyFrH7PSSoPUSzFBmtn686JE1iLIXqhOA3sxsp3yHbGmLCjo8T3n
tqNceK2Q0xtjbDcOCNMHFQV60b6pv6LOYjGneuJKYaHFL/kN9VH/zEqO/lsu7Jmg
MzD5OHltkP+S70hX+0XKRLCKzX0lgvFB32b1F1QUQ9cCAwEAATANBgkqhkiG9w0B
AQsFAAOCAgEAZ0vv/p3JH1V7gCmYRTZf36BkjJm4zdy4cEz0qCfDdBJRBQhmi8eQ
nWXQU8RYqo6aLKQFusbzEaffhyokIp1b1njaElxIDc4AU8B2ljF3mbzDZWoruQaG
VN2AS1GSXIXR2gSrofFAS66+Vr21Qh2yHyK6LoOYkXegj6aK4dGwIRHd0SwpEcL2
uRFsuWgEiTet8VkZz56zGe4m9cM6Dhnyhe+SEGhOsx4hwbLbS1nIafp0+Cfw/YP2
NskN6kFhz7yrM898n/sZbyoFtX+f+XZtRZu1My6McCRxyioN5KhdE5nMAsbkCG2M
ToOi1+u6oFsc8p6JroxP/3qozSAu9M6pa2JH+6xsemuXOat3cMbuhExuuFOqSxjx
eU4B5V+9TwYMGgwB6NZA2M6V1Ux7w/sAzwpYg62EBJeNIwURUDR1aHfzSokPlTOR
5vgbsYTEAhvut9iv7XPIyNGamr1+i4wt7LjTXiaYYYoPyq+MsFjTk0sVg+Y0ep4D
sAk9FtlRkWEo4ELLaASNGrswAcL0l5w8lzUaNH3ZdNDVX7wapK6ih69NxyoUXgAT
KD3CJDYn4EsJt9hG7gXnrNfZoGfy0gsoYCYl57EW0YyZkfiWMikrePXphAm05vOq
m2dX6Ui4nfbXHtTJdIYhpxpJ3/CNsCXN3Fmus0GF9YlsZFeUxPWHQ5I=
-----END CERTIFICATE-----" >> /kaniko/ssl/certs/ca-certificates.crt
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
